-- Create the projects table to store project metadata
CREATE TABLE IF NOT EXISTS projects (
    project_id TEXT PRIMARY KEY, -- Using dirname (e.g. this_project) as primary key
    project_type TEXT NOT NULL, -- Type of the project (web-static, web-app, game-2d, etc.)
    simple_description TEXT DEFAULT '', -- Short description for system status
    detailed_description TEXT DEFAULT '', -- Comprehensive description with file details
    file_system_structure JSONB, -- JSON representation of file structure
    repository_url TEXT, -- Optional URL to remote git repository
    is_generated BOOLEAN DEFAULT FALSE, -- Flag indicating if project was generated by MAGI
    is_ready BOOLEAN DEFAULT TRUE, -- Flag indicating if the project is ready for use
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for efficient queries
CREATE INDEX IF NOT EXISTS idx_projects_project_type ON projects(project_type);

-- Create the project history table to track changes
CREATE TABLE IF NOT EXISTS project_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id TEXT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    action TEXT NOT NULL, -- Description of the action performed
    details JSONB, -- Optional JSON with additional details about the change
    task_id TEXT, -- Optional ID of the task that made the change
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index for efficient project history queries
CREATE INDEX IF NOT EXISTS idx_project_history_project_id ON project_history(project_id);
CREATE INDEX IF NOT EXISTS idx_project_history_created_at ON project_history(created_at);

-- Add comments to explain the tables and fields
COMMENT ON TABLE projects IS 'Stores metadata about projects managed by MAGI';
COMMENT ON COLUMN projects.project_id IS 'Project dirname used as primary key (e.g. this_project)';
COMMENT ON COLUMN projects.project_type IS 'Type of project (web-static, web-app, game-2d, etc.)';
COMMENT ON COLUMN projects.simple_description IS 'Short description shown in system status';
COMMENT ON COLUMN projects.detailed_description IS 'Comprehensive description including file details';
COMMENT ON COLUMN projects.file_system_structure IS 'JSON representation of the project file structure';
COMMENT ON COLUMN projects.repository_url IS 'Optional URL to remote git repository';
COMMENT ON COLUMN projects.is_generated IS 'Flag indicating if the project was automatically generated by MAGI';
COMMENT ON COLUMN projects.is_ready IS 'Flag indicating if the project is ready for use';

COMMENT ON TABLE project_history IS 'Tracks changes made to projects';
COMMENT ON COLUMN project_history.project_id IS 'Reference to the project';
COMMENT ON COLUMN project_history.action IS 'Description of the action performed';
COMMENT ON COLUMN project_history.details IS 'Optional JSON with additional details about the change';
COMMENT ON COLUMN project_history.task_id IS 'Optional ID of the task that made the change';
