# Docker Compose configuration for MAGI System

services:
    # Postgres database service - shared among all projects/containers
    db:
        image: pgvector/pgvector:pg16
        container_name: magi-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - '5432:5432' # Expose default Postgres port
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - magi-network

    # Controller service - the main web interface and container manager
    magi-controller:
        container_name: magi-controller
        build:
            context: ./
            dockerfile: ./controller/docker/Dockerfile
            # Enable BuildKit features
            args:
                BUILDKIT_INLINE_CACHE: 1
        ports:
            - '3010:3010' # Expose web interface port
        volumes:
            - claude_credentials:/claude_shared:rw # For Claude auth
            - magi_output:/magi_output:rw # For output storage
            - custom_tools:/custom_tools:rw # Custom tools
            - ../:/external/host:rw # Mount parent directory for repo management
            - ./.env:/.env:ro # Mount .env file in parent directory (where server expects it)
            - /var/run/docker.sock:/var/run/docker.sock # Allow Docker-in-Docker
        env_file:
            - ./.env
        environment:
            - PORT=3010
            - HOST_HOSTNAME=magi-controller # Use service name for internal communication
            - NODE_ENV=development # Set environment to development
            - TZ=$(date +%Z) # Get host timezone - conversion handled in code
        networks:
            - magi-network
        stop_signal: SIGINT
        stop_grace_period: 15s
        restart: unless-stopped

    # Base service configuration for magi containers
    magi-engine:
        image: magi-engine:latest
        build:
            context: ./
            dockerfile: ./engine/docker/Dockerfile
            # Enable BuildKit features
            args:
                BUILDKIT_INLINE_CACHE: 1
        volumes:
            - ./engine/src:/app/src:rw # Mount source code for development hot reloading
            - claude_credentials:/claude_shared:rw
            - magi_output:/magi_output:rw
            - custom_tools:/custom_tools:rw
        env_file:
            - ./.env
        environment:
            - HOST_HOSTNAME=magi-controller # Use service name instead of host.docker.internal
            - CONTROLLER_PORT=3010
            - TZ=$(date +%Z) # Get host timezone - conversion handled in code
        networks:
            - magi-network
#        restart: unless-stopped
        profiles:
            - 'donotstart' # Prevents this service from starting automatically

networks:
    magi-network:
        driver: bridge

volumes:
    claude_credentials:
        name: claude_credentials
        external: true
    magi_output:
        name: magi_output
        external: true
    custom_tools:
        name: custom_tools
        external: true
    postgres_data:
        name: postgres_data
