# Docker Compose configuration for CI testing (without database)

services:
    # Controller service - the main web interface and container manager
    magi-controller:
        container_name: magi-controller
        build:
            context: ./
            dockerfile: ./controller/docker/Dockerfile
            # Enable BuildKit features
            args:
                BUILDKIT_INLINE_CACHE: 1
        ports:
            - '3010:3010' # Expose web interface port
        volumes:
            - claude_credentials:/claude_shared:rw # For Claude auth
            - magi_output:/magi_output:rw # For output storage
            - custom_tools:/custom_tools:rw # Custom tools
            - ../:/external/host:rw # Mount parent directory for repo management
            - ./.env:/.env:ro # Mount .env file in parent directory (where server expects it)
            - /var/run/docker.sock:/var/run/docker.sock # Allow Docker-in-Docker
        env_file:
            - ./.env
        environment:
            - PORT=3010
            - HOST_HOSTNAME=magi-controller # Use service name for internal communication
            - NODE_ENV=development # Set environment to development
            - UV_USE_IO_URING=0 # Fix for Node.js io_uring bug causing PTY disconnects
            # Override database URL to use the CI service
            - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/magi_test
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - magi-network
        stop_signal: SIGINT
        stop_grace_period: 15s
        restart: unless-stopped

networks:
    magi-network:
        driver: bridge

volumes:
    claude_credentials:
        name: claude_credentials
        external: true
    magi_output:
        name: magi_output
        external: true
    custom_tools:
        name: custom_tools
        external: true