import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { getServerSession } from 'next-auth';
import { SessionProvider } from './providers';
import './globals.css';
import Link from 'next/link';
import Logout from '../components/logout';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav className="bg-violet-500 h-12 text-white flex items-center p-4">
                    <div className="flex gap-x-4">
                        <Link href="/">Home</Link>
                        {!!session && <Logout />}
                        {!session && <Link href="/login">Login</Link>}
                        {!session && <Link href="/register">Register</Link>}
                    </div>
                </nav>
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    );
}
