export interface VoiceOption {
    id: string;
    name: string;
    provider: 'openai' | 'elevenlabs' | 'gemini';
    model: string;
    voice: string;
    description?: string;
    speed?: number;
}

export const VOICE_OPTIONS: VoiceOption[] = [
    // ElevenLabs Voices
    {
        id: 'elevenlabs-jessica',
        name: 'Jessica',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'jessica',
        description: 'Expressive female',
    },
    {
        id: 'elevenlabs-james',
        name: 'James',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'james',
        description: 'Australian male',
        speed: 1.0,
    },
    {
        id: 'elevenlabs-rachel',
        name: 'Rachel',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'rachel',
        description: 'Natural female',
    },
    {
        id: 'elevenlabs-domi',
        name: 'Domi',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'domi',
        description: 'Warm',
    },
    {
        id: 'elevenlabs-bella',
        name: 'Bella',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'bella',
        description: 'Youthful female',
    },
    {
        id: 'elevenlabs-antoni',
        name: 'Antoni',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'antoni',
        description: 'Professional male',
    },
    {
        id: 'elevenlabs-elli',
        name: 'Elli',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'elli',
        description: 'Friendly',
    },
    {
        id: 'elevenlabs-josh',
        name: 'Josh',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'josh',
        description: 'Deep male',
    },
    {
        id: 'elevenlabs-arnold',
        name: 'Arnold',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'arnold',
        description: 'Authoritative',
    },
    {
        id: 'elevenlabs-adam',
        name: 'Adam',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'adam',
        description: 'Narrative male',
    },
    {
        id: 'elevenlabs-sam',
        name: 'Sam',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'sam',
        description: 'Energetic male',
    },
    {
        id: 'elevenlabs-george',
        name: 'George',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'george',
        description: 'Distinguished',
    },
    {
        id: 'elevenlabs-laura',
        name: 'Laura',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'laura',
        description: 'Sophisticated female',
    },
    {
        id: 'elevenlabs-callum',
        name: 'Callum',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'callum',
        description: 'British male',
    },
    {
        id: 'elevenlabs-unreal',
        name: 'Unreal',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'unreal',
        description: 'Synthetic/Unique',
    },
    {
        id: 'elevenlabs-blondie',
        name: 'Blondie',
        provider: 'elevenlabs',
        model: 'eleven_turbo_v2_5',
        voice: 'blondie',
        description: 'Bright female',
    },

    // Gemini Voices
    {
        id: 'gemini-aoede',
        name: 'Aoede',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Aoede',
        description: 'Breezy',
    },
    {
        id: 'gemini-zephyr',
        name: 'Zephyr',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Zephyr',
        description: 'Bright',
    },
    {
        id: 'gemini-puck',
        name: 'Puck',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Puck',
        description: 'Upbeat',
    },
    {
        id: 'gemini-charon',
        name: 'Charon',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Charon',
        description: 'Informative',
    },
    {
        id: 'gemini-kore',
        name: 'Kore',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Kore',
        description: 'Firm',
    },
    {
        id: 'gemini-fenrir',
        name: 'Fenrir',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Fenrir',
        description: 'Excitable',
    },
    {
        id: 'gemini-leda',
        name: 'Leda',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Leda',
        description: 'Youthful',
    },
    {
        id: 'gemini-orus',
        name: 'Orus',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Orus',
        description: 'Firm',
    },
    {
        id: 'gemini-callirrhoe',
        name: 'Callirrhoe',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Callirrhoe',
        description: 'Easy-going',
    },
    {
        id: 'gemini-autonoe',
        name: 'Autonoe',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Autonoe',
        description: 'Bright',
    },
    {
        id: 'gemini-enceladus',
        name: 'Enceladus',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Enceladus',
        description: 'Breathy',
    },
    {
        id: 'gemini-iapetus',
        name: 'Iapetus',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Iapetus',
        description: 'Clear',
    },
    {
        id: 'gemini-umbriel',
        name: 'Umbriel',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Umbriel',
        description: 'Easy-going',
    },
    {
        id: 'gemini-algieba',
        name: 'Algieba',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Algieba',
        description: 'Smooth',
    },
    {
        id: 'gemini-despina',
        name: 'Despina',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Despina',
        description: 'Smooth',
    },
    {
        id: 'gemini-erinome',
        name: 'Erinome',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Erinome',
        description: 'Clear',
    },
    {
        id: 'gemini-algenib',
        name: 'Algenib',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Algenib',
        description: 'Gravelly',
    },
    {
        id: 'gemini-rasalgethi',
        name: 'Rasalgethi',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Rasalgethi',
        description: 'Informative',
    },
    {
        id: 'gemini-laomedeia',
        name: 'Laomedeia',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Laomedeia',
        description: 'Upbeat',
    },
    {
        id: 'gemini-achernar',
        name: 'Achernar',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Achernar',
        description: 'Soft',
    },
    {
        id: 'gemini-alnilam',
        name: 'Alnilam',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Alnilam',
        description: 'Firm',
    },
    {
        id: 'gemini-schedar',
        name: 'Schedar',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Schedar',
        description: 'Even',
    },
    {
        id: 'gemini-gacrux',
        name: 'Gacrux',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Gacrux',
        description: 'Mature',
    },
    {
        id: 'gemini-pulcherrima',
        name: 'Pulcherrima',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Pulcherrima',
        description: 'Forward',
    },
    {
        id: 'gemini-achird',
        name: 'Achird',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Achird',
        description: 'Friendly',
    },
    {
        id: 'gemini-zubenelgenubi',
        name: 'Zubenelgenubi',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Zubenelgenubi',
        description: 'Casual',
    },
    {
        id: 'gemini-vindemiatrix',
        name: 'Vindemiatrix',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Vindemiatrix',
        description: 'Gentle',
    },
    {
        id: 'gemini-sadachbia',
        name: 'Sadachbia',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Sadachbia',
        description: 'Lively',
    },
    {
        id: 'gemini-sadaltager',
        name: 'Sadaltager',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Sadaltager',
        description: 'Knowledgeable',
    },
    {
        id: 'gemini-sulafat',
        name: 'Sulafat',
        provider: 'gemini',
        model: 'gemini-2.5-flash-preview-tts',
        voice: 'Sulafat',
        description: 'Warm',
    },

    // OpenAI Voices
    {
        id: 'openai-sage',
        name: 'Sage',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'sage',
        description: 'Clear',
    },
    {
        id: 'openai-echo',
        name: 'Echo',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'echo',
        description: 'Male',
    },
    {
        id: 'openai-alloy',
        name: 'Alloy',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'alloy',
        description: 'Neutral',
    },
    {
        id: 'openai-ash',
        name: 'Ash',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'ash',
        description: 'Conversational',
    },
    {
        id: 'openai-coral',
        name: 'Coral',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'coral',
        description: 'Pleasant',
    },
    {
        id: 'openai-fable',
        name: 'Fable',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'fable',
        description: 'British',
    },
    {
        id: 'openai-nova',
        name: 'Nova',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'nova',
        description: 'Friendly',
    },
    {
        id: 'openai-onyx',
        name: 'Onyx',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'onyx',
        description: 'Deep',
    },
    {
        id: 'openai-shimmer',
        name: 'Shimmer',
        provider: 'openai',
        model: 'gpt-4o-mini-tts',
        voice: 'shimmer',
        description: 'Soft',
    },
];

// Default voice
export const DEFAULT_VOICE_ID = 'elevenlabs-jessica';

export function getVoiceById(id: string): VoiceOption | undefined {
    return VOICE_OPTIONS.find(voice => voice.id === id);
}
